#!/bin/bash

CLASSPATH="-cp .:lib/stanford-openie.jar:lib/stanford-openie-models.jar:lib/stanford-corenlp-3.5.2-models.jar:lib/stanford-corenlp-3.5.2.jar:bin"

# Remove *.class files if they exist
if [ -e *.class ]; then
  rm *.class
fi

# Run program
javac $CLASSPATH *.java
java $CLASSPATH Manager

# Clean up after running
rm *.class
