#!/bin/bash

# Author: Zach Wilson
#
# This script takes 1 argument, a target directory,
# which must be a real path. It then moves the project
# to the target directory and downloads the 4 JAR files to lib.

# Moves directory to new location
function move_directory() {
  cd ..
  mv $PROJECT $DIR/$PROJECT
  cd $DIR/$PROJECT
  echo "$PROJECT moved to $DIR"
}

# Download all JARs
function download_jars() {
  wget -P $LIB $CORE_NLP_CODE_URL -O $CORE_NLP_CODE
  wget -P $LIB $CORE_NLP_MODELS_URL -O $CORE_NLP_MODELS
  wget -P $LIB $OPEN_IE_CODE_URL -O $OPEN_IE_CODE
  wget -P $LIB $OPEN_IE_MODELS_URL -O $OPEN_IE_MODELS
}

# Checks to ensure JARs were downloaded properly
function check_for_jars() {

  # Check Core NLP Code
  if [ ! -e $LIB/$CORE_NLP_CODE ]; then
    echo "$CORE_NLP_CODE was not downloaded properly! Please retry download."
    exit
  fi

  # Check Core NLP Models
  if [ ! -e $LIB/$CORE_NLP_MODELS ]; then
    echo "$CORE_NLP_MODELS was not downloaded properly! Please retry download."
    exit
  fi

  # Check Open IE Code
  if [ ! -e $LIB/$OPEN_IE_CODE ]; then
    echo "$OPEN_IE_CODE was not downloaded properly! Please retry download."
    exit
  fi

  # Check Open IE Models
  if [ ! -e $LIB/$OPEN_IE_MODELS ]; then
    echo "$OPEN_IE_MODELS was not downloaded properly! Please retry download."
    exit
  fi
}

# Ensure only 1 argument was provided
if [ $# != 1 ]; then
  echo "Must specify target directory for installation. Target directory must be a real path to an existing directory."
  exit
fi

echo ""

DIR=${1%/}
PROJECT="abstractive-summarization-master"
LIB="$DIR/$PROJECT/lib/"

# Core NLP Code
CORE_NLP_CODE_URL="https://www.dropbox.com/s/9k20n7zfo1tcvpe/stanford-corenlp-3.5.2.jar?dl=0"
CORE_NLP_CODE="stanford-corenlp-3.5.2.jar"

# Core NLP Models
CORE_NLP_MODELS_URL="https://www.dropbox.com/s/b1351vjbn4m2sil/stanford-corenlp-3.5.2-models.jar?dl=0"
CORE_NLP_MODELS="stanford-corenlp-3.5.2-models.jar"

# Open IE Code
OPEN_IE_CODE_URL="https://www.dropbox.com/s/h9idy1tajdnupjv/stanford-openie.jar?dl=0"
OPEN_IE_CODE="stanford-openie.jar"

# Open IE Models
OPEN_IE_MODELS_URL="https://www.dropbox.com/s/dxd8olkkvix8enq/stanford-openie-models.jar?dl=0"
OPEN_IE_MODELS="stanford-openie-models.jar"

echo "Specified directory: $DIR"

# If the directory does not exist, create it
if [ ! -d "$DIR" ]; then
  echo "$DIR does not exist. Creating directory."
  mkdir "$DIR"
fi

# If directory exists, move project to target, and download JARs
if [ -d "$DIR" ]; then
  move_directory
  echo "Downloading Stanford JARs to $LIB"
  download_jars
  check_for_jars
  echo "Downloads successful. Setup complete."
else
  echo "Unable to create directory $DIR."
fi
