#!/bin/bash

# Author: Zach Wilson
#
# This script takes 1 argument, a target directory,
# which must be a real path. It then moves the project
# to the target directory and downloads the 4 JAR files to lib.

# Moves directory to new location
function move_directory() {
  cd ..
  mv $PROJECT $DIR/$PROJECT
  cd $DIR/$PROJECT
  echo "Project moved to $DIR"
}

# Download all JARs
function download_jars() {
  wget -P $LIB $CORE_NLP_CODE_URL
  wget -P $LIB $CORE_NLP_MODELS_URL
  wget -P $LIB $OPEN_IE_CODE_URL
  wget -P $LIB $OPEN_IE_MODELS_URL
}

# Checks to ensure JARs were downloaded properly
function check_for_jars() {

  # Check Core NLP Code
  if [ ! -e $LIB/$CORE_NLP_CODE ]; then
    echo "$CORE_NLP_CODE was not downloaded properly! Please retry download."
    exit
  fi

  # Check Core NLP Models
  if [ ! -e $LIB/$CORE_NLP_MODELS ]; then
    echo "$CORE_NLP_MODELS was not downloaded properly! Please retry download."
    exit
  fi

  # Check Open IE Code
  if [ ! -e $LIB/$OPEN_IE_CODE ]; then
    echo "$OPEN_IE_CODE was not downloaded properly! Please retry download."
    exit
  fi

  # Check Open IE Models
  if [ ! -e $LIB/$OPEN_IE_MODELS ]; then
    echo "$OPEN_IE_MODELS was not downloaded properly! Please retry download."
    exit
  fi
}

# Ensure only 1 argument was provided
if [ $# != 1 ]; then
  echo "Must specify target directory for installation. Target directory must be a real path to an existing directory."
  exit
fi

DIR=${1%/}
PROJECT="abstractive-summarization-master"
LIB="$DIR/$PROJECT/lib/"

# Core NLP Code
CORE_NLP_CODE_URL="http://download1319.mediafire.com/s7h5wr16gutg/c4vj44gry3rtc5y/stanford-corenlp-3.5.2.jar"
CORE_NLP_CODE="stanford-corenlp-3.5.2.jar"

# Core NLP Models
CORE_NLP_MODELS_URL="http://download1511.mediafire.com/diy980jkstwg/xc9dbguc2b3ieyt/stanford-corenlp-3.5.2-models.jar"
CORE_NLP_MODELS="stanford-corenlp-3.5.2-models.jar"

# Open IE Code
OPEN_IE_CODE_URL="http://download1079.mediafire.com/ax59huylm42g/sac45ys2uuux8n9/stanford-openie.jar"
OPEN_IE_CODE="stanford-openie.jar"

# Open IE Models
OPEN_IE_MODELS_URL="http://download1517.mediafire.com/tmceha171msg/qjqmhwzv574mp4l/stanford-openie-models.jar"
OPEN_IE_MODELS="stanford-openie-models.jar"

# If the directory exists, move directory, and download JARs
if [ -d "$DIR" ]; then
  echo "Specified directory: $DIR"
  move_directory
  echo "Downloading Stanford JARs to $LIB"
  download_jars
  check_for_jars
  echo "Downloads successful. Setup complete."
else
  echo "Directory does not exist! Please provide real path to existing directory."
fi
